repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types_or: [html]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5  # Ruff version
  hooks:
    - id: ruff
      types_or: [python, pyi, jupyter]
      args: [--fix]
    -   id: ruff-format
        types_or: [python, pyi, jupyter]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1  # Use the latest isort version
  hooks:
    - id: isort  # This will sort imports automatically
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
