repos:
- repo: local
  hooks:
    - id: poetry-update
      name: Poetry Update
      entry: poetry update
      language: system
      # Optional: specify types or files to trigger this hook
      # files: pyproject.toml
      # Always run this hook (not recommended for update; shown for illustrative purposes):
      always_run: true
      # Optional: prevent commit if the lock file changes
      stages: [pre-commit]
      pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types_or: [html]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", --line-length=72]
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
