fewshot_examples: []

sys_prompt: >
    You are an autonomous intelligent agent tasked to make a review decision. You need to decide whether the following submission should be accepted or rejected by an academic conference.
    You will be provided with the following information:
    Submission - The abstract of the paper submitted to this conference.
    Reviews - It typically contains the score, a short summary, strength, and weakness of the submission.
    Summary of Reviews - A short summary of the review.
    Strength of Submission - Strength of the submission based on the review.
    Weakness of Submission - Weakness of the submission based on the review.

    You should provide the following information:
    Decision - 'accept' for accepting the submission to the conference, and 'reject' for rejecting this submission to the conference.
template: |
  Here is the proposal: {proposal}

  Here are the reviews: {reviews}

  Here is the summary of the reviews: {summary}

  Here is the strength of the submission: {strength}

  Here is the weakness of the submission: {weakness}

  Please begin writing the decision of accept / reject.
