fewshot_examples:
- "Here is the proposal: We present a novel approach to sentiment analysis using a hybrid model that combines transformer-based language models with traditional lexicon-based methods. Our method, named SentiHybrid, achieves state-of-the-art performance on multiple benchmark datasets while maintaining interpretability.

  Here are the reviews:
  Reviewer 1 (Score: 7/10): The paper presents an interesting combination of deep learning and traditional methods. Strengths include improved performance and interpretability. Weaknesses are the limited analysis of computational complexity and lack of comparison with some recent methods.

  Reviewer 2 (Score: 8/10): Novel approach with promising results. The integration of lexicon-based methods with transformers is well-executed. However, the paper would benefit from more ablation studies and a larger-scale evaluation.

  Here are the rebuttals: We thank the reviewers for their insightful comments. We have added a detailed analysis of computational complexity and comparisons with recent methods, including BERT-based models. We've also conducted additional ablation studies and expanded our evaluation to include two more large-scale datasets.

  Here is the summary of the reviews: Both reviewers acknowledge the novelty and potential of the hybrid approach. The main concerns are about the depth of analysis and scale of evaluation.

  Here is the strength of the submission: Innovative combination of deep learning and traditional methods, improved performance, and maintained interpretability.

  Here is the weakness of the submission: Initially limited analysis of computational complexity, lack of comprehensive comparisons, and need for more extensive evaluation.

  Please begin writing the decision of accept / reject."

- "Decision: Accept"

- "Here is the proposal: This paper introduces a new graph neural network architecture, DynamicGNN, designed for temporal graph representation learning. Our method adapts to changing graph structures over time and demonstrates superior performance on various temporal graph tasks, including link prediction and node classification.

  Here are the reviews:
  Reviewer 1 (Score: 6/10): The paper addresses an important problem in temporal graph learning. The proposed method shows promise, but the experimental evaluation is limited. The comparison with baseline methods is insufficient, and the scalability of the approach is not well-demonstrated.

  Reviewer 2 (Score: 5/10): While the idea is interesting, the novelty of the approach is questionable. The paper lacks a thorough theoretical analysis, and the empirical results are not convincing enough. The writing could also be improved for clarity.

  Here are the rebuttals: We appreciate the reviewers' feedback. We have expanded our experimental evaluation to include more baseline methods and larger datasets. We've added a section on scalability analysis and improved the theoretical foundations of our approach. We've also worked on improving the clarity of our writing throughout the paper.

  Here is the summary of the reviews: Both reviewers acknowledge the importance of the problem but express concerns about the depth of evaluation, novelty, and theoretical grounding of the approach.

  Here is the strength of the submission: Addresses an important problem in temporal graph learning with a potentially adaptive approach.

  Here is the weakness of the submission: Limited experimental evaluation, questionable novelty, lack of theoretical analysis, and issues with clarity in writing.

  Please begin writing the decision of accept / reject."

- "Decision: Reject"

sys_prompt: >
    You are an autonomous intelligent agent tasked to make a review decision. You need to decide whether the following submission should be accepted or rejected by an academic conference.
    You will be provided with the following information:
    Submission - The abstract of the paper submitted to this conference.
    Reviews - It typically contains the score, a short summary, strength, and weakness of the submission.
    Rebuttals - Written by the author to address the weaknesses of the submission mentioned in the reviews.
    Summary of Reviews - A short summary of the review.
    Strength of Submission - Strength of the submission based on the review.
    Weakness of Submission - Weakness of the submission based on the review.

    You should provide the following information:
    Decision - 'accept' for accepting the submission to the conference, and 'reject' for rejecting this submission to the conference.
template: |
  Here is the proposal: {proposal}

  Here are the reviews: {reviews}

  Here are the rebuttals: {rebuttals}

  Here is the summary of the reviews: {summary}

  Here is the strength of the submission: {strength}

  Here is the weakness of the submission: {weakness}

  Please begin writing the decision of accept / reject.
