name: deploy to aws ec2 backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/UIUC.pem
        chmod 600 /tmp/UIUC.pem
        eval "$(ssh-agent -s)"
        ssh-add /tmp/UIUC.pem

    - name: deploy to ec2
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/UIUC.pem ubuntu@ec2-54-89-143-231.compute-1.amazonaws.com << 'EOF'
          cd ~/research-town/backend/
          conda activate research_town
          git pull origin main
          tmux send-keys -t 0 C-c
          sleep 5
          tmux send-keys -t 0 "uvicorn main:app --host 127.0.0.1 --port 8000" C-m
        EOF
